connectedin/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfis.urls')),
    path('registrar/', RegistrarUsuarioView.as_view(template_name='registrar.html'), name='registrar'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

perfis/urls.py
from django.urls import path
from perfis import views

urlpatterns = [
    path('', views.timeline, name='index'),
    path('perfil/', views.contatos, name='contatos'),
    path('perfil/<int:perfil_id>', views.exibir_perfil, name='exibir'),
    path('perfil/<int:perfil_id>/convidar', views.convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar', views.aceitar, name='aceitar'),
    path('publicar/', views.PublicarPostView.as_view(), name='publicar'),
    path('minha-timeline/', views.timeline_pessoal, name='timeline_pessoal'),
    path('perfil/<int:perfil_id>/timeline/', views.timeline_amigo, name='timeline_amigo')
]

perfis/models.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, related_name='perfil', on_delete=models.CASCADE)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)

    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        convite = Convite(solicitante=self, convidado=perfil_convidado)
        convite.save()

    def obter_timeline(self):
        return Post.objects.filter(profile=self).order_by('-criado_em')

    def __str__(self):
        return f'{self.nome}({self.usuario.username})'


class Convite(models.Model):
    solicitante = models.ForeignKey(
        Perfil,
        on_delete=models.CASCADE,
        related_name='convites_feitos'
    )

    convidado = models.ForeignKey(
        Perfil,
        on_delete=models.CASCADE,
        related_name='convites_recebidos'
    )

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()


class Postagem():
    texto = models.TextField()
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)


    def __str__(self):
        return f'Postagem {self.profile.nome} - {self.created_at}'

usuarios/models.py
from django.db import models

# Create your models here.

perfis/forms.py
from django import forms


class CriarPostagemForm(forms.Form):
    texto = forms.CharField(required=True)

    def is_valid(self):
        valido = True
        if not super(CriarPostagemForm, self).is_valid():
            self.adicionar_erro('Verifique os dados informados')
            valido = False

        return valid

    def adicionar_erro(self, mensagem):
        erros = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())

        erros.append(message)

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)


    def is_valid(self):
        valido = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Verifique os dados submetidos')
            valido = False

        usuario_ja_existe = User.objects.filter(username=self.cleaned_data['nome']).exists()
        if usuario_ja_existe:
            self.adicionar_erro('Usuário já existente')
            valido = False
        return valido


    def adicionar_erro(self, mensagem):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(mensagem)

perfis/views.py
from django.shortcuts import render
from perfis.models import Perfil, Convite, Postagem
from django.shortcuts import redirect
from django.views.generic.base import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from perfis.forms import CriarPostagemForm
from django.contrib import messages


@login_required
def contatos(request):
    dados = {
        'perfis': Perfil.objects.all().exclude(usuario=request.user)
    }
    return render(request, 'contatos.html', dados)


@login_required
def exibir_perfil(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    meu_perfil = Perfil.objects.get(usuario=request.user)
    ja_eh_contato = perfil in meu_perfil.contatos.all()
    aguardando_aceitar = Convite.objects.filter(solicitante=meu_perfil, convidado=perfil)
    dados = {
        'perfil': perfil,
        'ja_eh_contato': ja_eh_contato,
        'aguardando_aceitar': aguardando_aceitar
    }
    return render(request, 'perfil.html', data)


@login_required
def convidar(request, perfil_id):
    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    request.user.perfil.convidar(perfil_a_convidar)
    return redirect('index')


@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')


class PublicarPostView(View):
    template_name = 'publicar.html'


    @method_decorator(login_required)
    def get(self, request):
        return render(request, self.template_name)


    @method_decorator(login_required)
    def post(self, request):
        form = CriarPostagemForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            perfil = get_object_or_404(Perfil, usuario=self.request.user)
            Postagem.objects.create(
                texto=cleaned_data['texto'],
                perfil=perfil
            )
            return redirect('index')
        return render(request, self.template_name, {'form': form})


@login_required
def timeline(request):
    dados = {
        'postagens': Post.objects.all().order_by('-criado_em'),
        'titulo': 'Timeline'
    }
    return render(request, 'timeline.html', dados)


@login_required
def timeline_pessoal(request):
    dados = {
        'postagens': Post.objects.filter(perfil__usuario=request.user).order_by('-criado_em'),
        'titulo': 'Timeline pessoal'
    }
    return render(request, 'timeline.html', data)


@login_required
def timeline_amigo(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    meu_perfil = Perfil.objects.get(usuario=request.user)
    eh_contato = perfil in meu_perfil.contatos.all()
    if not eh_contato:
        messages.info(request, 'Você só pode ver a timeline de seu contatos!')
        return redirect('index')
    dados = {
        'postagens': Post.objects.filter(perfil=perfil).order_by('-criado_em'),
        'titulo': f'Timeline {perfil.nome}'
    }
    return render(request, 'timeline.html', dados)

usuarios/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.models import User
from django.shortcuts import redirect
from usuarios.forms import RegistrarUsuarioForm
from perfis.models import Perfil


class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)


    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            usuario = User(username=cleaned_data['nome'], email=cleaned_data['email'])
            usuario.set_password(cleaned_data['senha'])
            usuario.save()

            Perfil.objects.create(
                nome=cleaned_data['nome'],
                telefone=cleaned_data['telefone'],
                nome_empresa=cleaned_data['nome_empresa'],
                usuario=usuario
            )
            return redirect('index')
        return render(request, self.template_name, {'form': form})

perfis/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
    <title>ConnectedIN</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <div class="header" >
        <ul class="nav nav-pills pull-right" >
            <li class="" > <a href="{% url 'index' %}">Timeline</a> </li>
            <li class="" > <a href="{% url 'contatos' %}">Contatos</a> </li>
            <li class="" > <a href="{% url 'publicar' %}">Publicar</a> </li>
            <li class="" > <a href="{% url 'timeline_pessoal' %}">Timeline pessoal</a> </li>
            <li class="" > <a href="{% url 'logout' %}">Logout</a> </li>
        </ul>
        <h3> <a class="" href="{% url 'index' %}">ConnectedIn</a> </h3>
    </div>
    <div class="container" >
        <div class="row content" >
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

perfis/templates/contatos.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Todos os perfis</strong>
        </div>

        {%  if perfis %}
            <ul>
                {%  for perfil in perfis  %}
                <li>
                    <a href="{% url 'exibir' perfil.id %}">
                        {{ perfil.nome }}

                    </a> / {{ perfil.email }}
                </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Nenhum Perfil encontrado</p>
        {% endif %}
    </div>

    <div class="panel panel-default">
        {% with total_de_convites=user.perfil.convites_recebidos.count %}
            {% if total_de_convites %}
                <div class="panel-heading">
                    <strong>
                        Você tem
                        {{ total_de_convites }} convite{{ total_de_convites|pluralize }}
                        aguardando aprovação
                    </strong>
                </div>
                <ul class="list-group">
                    {% for convite in user.perfil.convites_recebidos.all %}
                        <li class="list-group-item">
                            {{ convite.solicitante.nome }}
                            <a href="{% url 'aceitar' convite.id %}" class="pull-right">aceitar</a>
                        </li>
                    {% endfor %}
                </ul>
                {% else %}
                    <div class="panel-body">
                        <p>Nenhum convite recebido :(</p>
                    </div>
            {% endif %}
        {% endwith %}
    </div>

    <div class="panel panel-default">
        {% with total_de_contatos=user.perfil.contatos.count %}
            {% if total_de_contatos %}
                <div class="panel-heading">
                    <strong>Você tem {{total_de_contatos}}
                        contato{{ total_de_contatos|pluralize }}
                    </strong>

                </div>
                <ul class="list-group">
                    {% for contato in user.perfil.contatos.all %}
                        <a href="{% url 'exibir' contato.id %}" class="list-group-item">{{ contato.nome }} //
                        {{ contato.email }}</a>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    <p>Você não possui contatos no momento :(</p>
                </div>
            {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock %}

perfis/templates/perfil.html
{% extends "base.html" %}
{% block body %}
<div class="row">
    <div class="col-lg-12">
        <h2 style="margin-top:0">{{ perfil.nome }}</h2>
        <address>
            <strong>{{ perfil.nome_empresa }}</strong><br />
            <abbr title="Telefone">Tel:</abbr> {{perfil.telefone}}<br />
            <a href="mailto:{{perfil.email}}">{{perfil.email}}</a><br /><br />
            <a class="btn btn-sm btn-primary" href="{% url 'timeline_amigo' perfil.id %}">Timeline</a>
        </address>

        {% if ja_eh_contato %}
            <div class="well well-sm">Vocês estão conectados!</div>
        {% elif aguardando_aceitar %}
            <div class="well well-sm">Aguardando aceitar o convite</div>
        {% else %}
            <a href="{% url 'convidar' perfil.id %}" class="btn btn-success" role="button">convidar</a>
        {% endif %}
    </div>
</div>
{% endblock %}

perfis/templates/publicar.html
{% extends "base.html" %}
{% block body %}
<form class="form-post" action="{% url 'publicar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-post-heading">Publicar postagem</h2>
    <textarea name="texto" id="id_texto" rows="10" required ></textarea>
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Publicar</button>
    {% if form.errors %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            {{form.non_field_errors}}
        </div>
    {% endif %}
</form>
{% endblock %}

perfis/templates/timeline.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">
    {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %} class="alert alert-warning {{ message.tags }}"{% endif %} role="alert">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <div class="panel panel-default timeline-bg">
        <div class="panel-heading">
            <strong>{{titulo}}</strong>
        </div>

        {%  for postagem in postagens  %}
            <div class="post" >
                <span class="autor" >{{ postagem.perfil.nome }}</span>
                <p>{{ postagem.texto }}</p>
                <span class="data" >{{ postagem.created_at | date }}</span>
                <a class="btn btn-primary" href="">Ver perfil</a>
            </div>
        {% empty %}
        <div class="post" >
            <p>Nenhuma postagem encontrada</p>
        </div>
        {%  endfor %}
    </div>
</div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>ConnectedIn</title>
    <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'styles/signin.css' %}" rel="stylesheet">
    <link href="{% static 'styles/main.css' %}" rel="stylesheet">
</head>

<body>
    <div class="header" >
        <ul class="nav nav-pills pull-right" >
            <li class="" > <a href="{% url 'login' %}">Login</a> </li>
            <li class="" > <a href="{% url 'registrar' %}">Registrar-se</a> </li>
        </ul>
        <h3> <a href="{% url 'index' %}">ConnectedIn</a> </h3>
    </div>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}
{% block body %}
<form class="form-signin" role="form" action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Login</h2>
    <input id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>
    <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
    {% if form.errors %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            Verifique o email e/ou senha informados
        </div>
    {% endif %}
</form>
{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
<form class="form-signin" action="{% url 'registrar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Crie seu usuário</h2>
    <input id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>
    <input id="id_nome" name="nome" class="form-control" placeholder="Nome *" required>
    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>
    <hr />
    <input id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" required>
    <input id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa" required>
    <hr />
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>
    {% if form.errors %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            {{form.non_field_errors}}
        </div>
    {% endif %}
</form>
{% endblock %}